// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCatzRNE6xSvPYOXIUhG9s2pkJJZ6dPgZM',
    appId: '1:716971931336:web:0544d1c676e72a8ea557fd',
    messagingSenderId: '716971931336',
    projectId: 'notificacionespush-62db3',
    authDomain: 'notificacionespush-62db3.firebaseapp.com',
    storageBucket: 'notificacionespush-62db3.appspot.com',
    measurementId: 'G-LDZBG58QNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVRcEA3wDADnBq2g7HXxPifP40Si6XTZI',
    appId: '1:716971931336:android:000f8c2176a276a9a557fd',
    messagingSenderId: '716971931336',
    projectId: 'notificacionespush-62db3',
    storageBucket: 'notificacionespush-62db3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSMAYuM2iFzwczO8QJrOxgl-iocpomuI4',
    appId: '1:716971931336:ios:05c766d85f03ed1da557fd',
    messagingSenderId: '716971931336',
    projectId: 'notificacionespush-62db3',
    storageBucket: 'notificacionespush-62db3.appspot.com',
    iosBundleId: 'com.hackersucab2023.todayversion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSMAYuM2iFzwczO8QJrOxgl-iocpomuI4',
    appId: '1:716971931336:ios:3937429bb5545688a557fd',
    messagingSenderId: '716971931336',
    projectId: 'notificacionespush-62db3',
    storageBucket: 'notificacionespush-62db3.appspot.com',
    iosBundleId: 'com.hackersucab2023.todayversion.RunnerTests',
  );
}
